// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, Build R1)
// Generated source version: 1.1.3

package it.cnr.icar.eric.common.jaxrpc.cms.validation.client;

public interface ContentValidationServicePortType extends java.rmi.Remote {
    public javax.xml.soap.SOAPElement validateContent(javax.xml.soap.SOAPElement partValidateContentRequest) throws 
         java.rmi.RemoteException;
}
