// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, Build R1)
// Generated source version: 1.1.3

package it.cnr.icar.eric.common.jaxrpc.cms.validation.client;

import javax.xml.rpc.*;

public interface ContentValidationServiceSOAPService extends javax.xml.rpc.Service {
    public it.cnr.icar.eric.common.jaxrpc.cms.validation.client.ContentValidationServicePortType getContentValidationServicePort() throws ServiceException;
}
