// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package it.cnr.icar.eric.common.jaxrpc.registry.client;

import javax.xml.rpc.*;

public interface EbXMLRegistrySOAPService extends javax.xml.rpc.Service {
    public it.cnr.icar.eric.common.jaxrpc.registry.client.QueryManagerPortType getQueryManagerPort() throws ServiceException;
    public it.cnr.icar.eric.common.jaxrpc.registry.client.LifeCycleManagerPortType getLifeCycleManagerPort() throws ServiceException;
}
